### ISSUE TITLE
Ensure each of the two devices on the power node PCB work correctly, datalog the results

### ISSUE THREAD

**Issue by omegabytes** [rLoopTeam/eng-software-pod#39]
this is too broad

**Comment by m4rol** [comment]
Description of DS2482 https://www.maximintegrated.com/en/products/interface/controllers-expanders/DS2482-100.html

**Comment by SafetyLok** [comment]
The power node has two DS2482 devices on board. They share the same I2C bus, but have different addresses. The purpose is that we will split some of the 1-wire devices onto one bus, and some other DS18B20 devices onto other bus.  It will help a bit with redundancy.

We need to verify that both devices work correctly together in hardware. We need to datalog (using an iLogic or otherwise) to ensure that the I2C bus time is shared correctly.

From the software viewpoint we need to ensure that the devices which have been enumerated and are tagged to one 1-wire bus are not confused with the other bus, as a search failure will take time.

**Comment by rjvyas** [comment]
@SafetyLok could you please check @nemimccarter's code in #40. I think this issue is already address in the code: if (s16DS2482S_SEARCH__Search(u8DeviceIndex))

**Comment by SafetyLok** [comment]
Need to test this on actual hardware with all the sensors loaded.
